### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Grienauer** [ahenry91/pebble_url_launcher#3]
Which license has this project?
Would be great if you could add it in the readme.

THX!

**Comment by Grienauer** [comment]
Is there any progress?
I want to publish an open source project, but I can't. I have to know, if I could use your code before...
thx!

**Comment by andymitchhank** [comment]
Sorry for the delay. Not much time to check this repo. I have added a MIT license file to the repo. Do let me know when you publish your project so I can check it out.
